name: Build nightly SNAPSHOT

on:
  schedule:
    # Midnight every day
    - cron: "0 0 * * *"
  push:
    # Rerun if workflow changes
    branches:
      - 'master'
    paths:
      - '**/snapshot.yml'

jobs:
  gradle:
    name: Publish nightly snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Publish
        env:
          PROPS_RELEASE: "-Prelease=false -PskipJavadoc -PskipSpotless"
          PROPS_NEXUS: "-PcentralSnapshotUsername=${{ secrets.CENTRAL_PORTAL_USERNAME }} -PcentralSnapshotPassword=${{ secrets.CENTRAL_PORTAL_PASSWORD }}"
          PROPS_SIGNING: "-PuseInMemoryKey=true -Psigning.inMemoryKey=${{ secrets.IN_MEMORY_KEY }} -Psigning.password=${{ secrets.SIGNING_PASSWORD }}"
          PROPS_GITHUB: "-PgithubAccessToken=${{ secrets.GITHUB_TOKEN }}"
        run: ./gradlew publishAllPublicationsToCentralSnapshotsRepository $(echo $PROPS_RELEASE $PROPS_GIT $PROPS_NEXUS $PROPS_SIGNING $PROPS_GITHUB) -x test
